### ISSUE TITLE
Chat not show when using Youtube brand account

### ISSUE THREAD

**Issue by sakuyamaij** [Shad02w/Youtube-Chat-in-Fullscreen#1]
I installed the extension and found it did not work on my chrome.
But working on incognito mode.

With half hour test, I found fullscreen chat box only not show when using Youtube brand account.
After I switch to Google account, fullscreen chat box works again.
(Youtube brand account belongs to my google account)

Can you check it and make it available when using youtube brand account?
Thank you peko~

**Comment by Shad02w** [comment]
Hi @sakuyamaij , it seem like some sort of authentication problem, I will try to fix it in next update, Thanks for your time to do the testing peko~
