### ISSUE TITLE
Ctrl + Alt + C Doesn't seem to work

### ISSUE THREAD

**Issue by zwamdurkel** [Shad02w/Youtube-Chat-in-Fullscreen#12]
When pressing CTRL + ALT + C the overlay doesn't toggle.

Expected behaviour: the visibility of the overlay is toggled when pressing the key combination

I can confirm this behaviour on Chrome and Brave.

**Comment by Shad02w** [comment]
This shortcut will change to CTRL + SHIFT + Y next version, since previous shortcut is not working on some device like mac.
