### ISSUE TITLE
Some chats do not render the chat window at all due to `message.runs` being undefined

### ISSUE THREAD

**Issue by ekumlin** [Shad02w/Youtube-Chat-in-Fullscreen#19]
In some chats, the overlay does not appear at all. The following shows up in the console:

![image](https://user-images.githubusercontent.com/1350074/134453996-a4d49d79-a777-425c-a5fa-247f3db66846.png)

Which points to this, when formatted:

![image](https://user-images.githubusercontent.com/1350074/134454040-9633e1da-a3e1-4930-88a1-b276544330a0.png)

The `runs` property simply does not exist on this message.

![image](https://user-images.githubusercontent.com/1350074/134454083-ca2683d9-1ac5-4a69-b66b-9df2e541544f.png)

To be honest, I've no idea what kind of message actually causes this. But it looks like some kind of `simpleText` field is getting pushed as a message. From the above, I looked for "Pokioo" on the page and found that it looks like the super chats have that text in them:

![image](https://user-images.githubusercontent.com/1350074/134454655-12e1b78b-f4c2-4aa2-b89f-5ca9f26382d3.png)

Not sure if this is an update to YouTube that caused this to break, or what, but it seems to completely cripple the overlay.

**Comment by miraidave** [comment]
I believe it's due to the new youtube function, "Free Member Milestone Chat".  It looks like a green superchat but the it shows the membership duration instead of dollar amount.  This difference is probably what's causing the issue.

**Comment by Shad02w** [comment]
@miraidave  Is there any way i can find a stream with "Free Member Milestone Chat" ? so far I watch a few streams and havent found one.

**Comment by Shad02w** [comment]
@ekumlin It will be better if you can send me the link of the stream and time for me to test it

**Comment by miraidave** [comment]
Here's a link with Free Member Milestone Chats: https://www.youtube.com/watch?v=W7gUkrx2KPk

**Comment by ekumlin** [comment]
Another option is [this video](https://www.youtube.com/watch?v=udGs-6Aay9M) at around 0:52.

**Comment by Shad02w** [comment]
v2.0.3 has been published, this bug should be fixed in ab4c9cad7a1b525a7c931db72ccf39c8bca2d11.  If there is no futher problems, I am goning to close this issue

**Comment by ekumlin** [comment]
Looks fixed to me.
