### ISSUE TITLE
Resize the overlay

### ISSUE THREAD

**Issue by lekoOwO** [Shad02w/Youtube-Chat-in-Fullscreen#3]
Is it possible to resize the overlay? I'd like it to occupie the whole right half screen lol

Thanks for your wonderful plugin!

**Comment by Shad02w** [comment]
Yes, you can definitely resize the overlay by dragging right bottom corner, dont know whether it can totally fits your needs.

<img src="https://user-images.githubusercontent.com/6605655/99897827-cf279280-2cd7-11eb-9397-84c7c181b14e.png" width="560"/>

**Comment by lekoOwO** [comment]
Ohhh I see.

Thanks!
